### ISSUE TITLE
Set timezone not working

### ISSUE THREAD

**Issue by MrAliev** [MassTransit/docker-rabbitmq#3]
How can I set a time zone when running an image in docker? 
Setting the environment variable in "docker-compose.yml" file
```
rabbitmq:
    image: masstransit/rabbitmq
    environment:
      TZ: 'Europe/Berlin'
...
```
does not lead to the desired result
